import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {Link} from '../components/Link'
import {Headline} from '../components/Headline'
import header from '../components/header'

//import Link.js

import {Main} from '../components/main'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cosmic dance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header />
      <Main page="indexpage" />
      
    </>
  )
}
