import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {Headline} from '../components/Headline'
import Header from '../components/header'
import {Main} from '../components/main'

//export header component
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Inter />
      </Head>
      <Header />
      <Headline />
      <Main />
    </div>
  )
}
  

//load markdown file in posts folder using fs module and readdirSync
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Link from 'next/link'
import PostCard from '../components/postcard'

export const getStaticProps=() => {
  const files = fs.readdirSync('posts')
  const posts=files.map(filename => {
    // Create slug from filename
    const slug = filename.replace('.md', '')
  const fileContent=
  fs.readFileSync(`posts/${filename}`, 'utf-8');
  const {data, content}=matter(fileContent)
    console.log('slug', slug)
    console.log('data', data)
    console.log('content', content)
    return{
      slug,
      frontMatter: data,
    }

})
  return{
    props: {
      posts,
    }
  }
}



    

export default function Home({ posts }) {
  return (
    <div className="my-8">
      <div className="grid grid-cols-3">
        {posts.map((post) => (
          <PostCard key={post.slug} post={post} />
        ))}
      </div>
    </div>
  );
}
